#!/usr/bin/env python

from blackjack import Blackjack

def main():
    print """
*****************************
    Welcome to Blackjack!
*****************************
"""

    dollars = 500
    bet = 5
    cmd = ''

    while cmd != 'q':
        print "You have %d dollars" % dollars
        print "What's your bet? (Hit return to bet %d dollars)" % bet
        raw_bet = raw_input()
        if raw_bet:
            try:
                bet = int(raw_bet)
            except ValueError:
                print "Bet has to be a number"
                continue

        if not bet:
            print "You have to bet something!"
        elif bet > 100:
            print "The max bet is 100"
        elif bet > dollars:
            print "You can't bet more than you have!"
        else:

            bj = Blackjack()

            while bj.status == 'playing':
                print "Dealer's hand: %s" % bj.dealer.hidden()
                print "Your hand: %s (%d)" % (bj.player, bj.player.score())

                print "Hit 'h' to hit or anything else to stand"
                choice = raw_input()
                if choice.startswith('h'):
                    bj.hit()
                else:
                    bj.stand()

            print ""

            if bj.dealer.score() > 21:
                print "Dealer busts!"
            elif bj.player.score() > 21:
                print "Bust!"

            print "Dealer's hand: %s (%d)" % (bj.dealer, bj.dealer.score())
            print "You had %s (%d)\n" % (bj.player, bj.player.score())

            if bj.status == "house":
                dollars -= bet
                print "Dealer wins."
            elif bj.status == 'player':
                dollars += bet
                print "You win!"
            elif bj.status == 'blackjack':
                dollars += int(1.5 * bet)
                print "BLACKJACK!!"
            else:
                print "Push"

        print "\n"

        if dollars == 0:
            print "You have lost. Please make your way to the exits or an ATM."
            exit()

if __name__ == '__main__':
    main()
